//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace REH_Presentacion.Reportes {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRolIngresos")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRolIngresos : global::System.Data.DataSet {
        
        private RolEgresosDataTable tableRolEgresos;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public dsRolIngresos() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected dsRolIngresos(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RolEgresos"] != null)) {
                    base.Tables.Add(new RolEgresosDataTable(ds.Tables["RolEgresos"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RolEgresosDataTable RolEgresos {
            get {
                return this.tableRolEgresos;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsRolIngresos cln = ((dsRolIngresos)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RolEgresos"] != null)) {
                    base.Tables.Add(new RolEgresosDataTable(ds.Tables["RolEgresos"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableRolEgresos = ((RolEgresosDataTable)(base.Tables["RolEgresos"]));
            if ((initTable == true)) {
                if ((this.tableRolEgresos != null)) {
                    this.tableRolEgresos.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsRolIngresos";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRolIngresos.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRolEgresos = new RolEgresosDataTable();
            base.Tables.Add(this.tableRolEgresos);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeRolEgresos() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRolIngresos ds = new dsRolIngresos();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void RolEgresosRowChangeEventHandler(object sender, RolEgresosRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RolEgresosDataTable : global::System.Data.TypedTableBase<RolEgresosRow> {
            
            private global::System.Data.DataColumn columnID;
            
            private global::System.Data.DataColumn columnCEDULA;
            
            private global::System.Data.DataColumn columnEMPLEADO;
            
            private global::System.Data.DataColumn columnDEPARTAMENTO;
            
            private global::System.Data.DataColumn columnDIAS_LABORADOS;
            
            private global::System.Data.DataColumn columnTOTAL_INGRESOS_IESS;
            
            private global::System.Data.DataColumn columnTOTAL_INGRESOS_NO_IESS;
            
            private global::System.Data.DataColumn columnTOTAL_INGRESOS;
            
            private global::System.Data.DataColumn columnAPORTE_IESS_EMPLEADO;
            
            private global::System.Data.DataColumn columnAPORTE_IESS_CONYUGE_EMPLEADO;
            
            private global::System.Data.DataColumn columnANTICIPO_SUELDO;
            
            private global::System.Data.DataColumn columnANTICIPO_ALIMENTACION;
            
            private global::System.Data.DataColumn columnDESCUENTO_DE_HABERES;
            
            private global::System.Data.DataColumn columnDESCUENTO_CELULAR;
            
            private global::System.Data.DataColumn columnVACACIONES_PAGADAS;
            
            private global::System.Data.DataColumn columnPRESTAMO_HIPOTECARIO;
            
            private global::System.Data.DataColumn columnPRESTAMO_QUIROGRAFARIO;
            
            private global::System.Data.DataColumn columnPRESTAMO_INTERNO;
            
            private global::System.Data.DataColumn columnRETENCION_JUDICIAL;
            
            private global::System.Data.DataColumn columnOTROS_EGRESOS;
            
            private global::System.Data.DataColumn columnNETO_A_RECIBIR;
            
            private global::System.Data.DataColumn columnIMPUESTO_A_LA_RENTA;
            
            private global::System.Data.DataColumn columnTOTAL_EGRESOS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosDataTable() {
                this.TableName = "RolEgresos";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal RolEgresosDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected RolEgresosDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CEDULAColumn {
                get {
                    return this.columnCEDULA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn EMPLEADOColumn {
                get {
                    return this.columnEMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DEPARTAMENTOColumn {
                get {
                    return this.columnDEPARTAMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DIAS_LABORADOSColumn {
                get {
                    return this.columnDIAS_LABORADOS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TOTAL_INGRESOS_IESSColumn {
                get {
                    return this.columnTOTAL_INGRESOS_IESS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TOTAL_INGRESOS_NO_IESSColumn {
                get {
                    return this.columnTOTAL_INGRESOS_NO_IESS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TOTAL_INGRESOSColumn {
                get {
                    return this.columnTOTAL_INGRESOS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn APORTE_IESS_EMPLEADOColumn {
                get {
                    return this.columnAPORTE_IESS_EMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn APORTE_IESS_CONYUGE_EMPLEADOColumn {
                get {
                    return this.columnAPORTE_IESS_CONYUGE_EMPLEADO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ANTICIPO_SUELDOColumn {
                get {
                    return this.columnANTICIPO_SUELDO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ANTICIPO_ALIMENTACIONColumn {
                get {
                    return this.columnANTICIPO_ALIMENTACION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DESCUENTO_DE_HABERESColumn {
                get {
                    return this.columnDESCUENTO_DE_HABERES;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DESCUENTO_CELULARColumn {
                get {
                    return this.columnDESCUENTO_CELULAR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn VACACIONES_PAGADASColumn {
                get {
                    return this.columnVACACIONES_PAGADAS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PRESTAMO_HIPOTECARIOColumn {
                get {
                    return this.columnPRESTAMO_HIPOTECARIO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PRESTAMO_QUIROGRAFARIOColumn {
                get {
                    return this.columnPRESTAMO_QUIROGRAFARIO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PRESTAMO_INTERNOColumn {
                get {
                    return this.columnPRESTAMO_INTERNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn RETENCION_JUDICIALColumn {
                get {
                    return this.columnRETENCION_JUDICIAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn OTROS_EGRESOSColumn {
                get {
                    return this.columnOTROS_EGRESOS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn NETO_A_RECIBIRColumn {
                get {
                    return this.columnNETO_A_RECIBIR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn IMPUESTO_A_LA_RENTAColumn {
                get {
                    return this.columnIMPUESTO_A_LA_RENTA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TOTAL_EGRESOSColumn {
                get {
                    return this.columnTOTAL_EGRESOS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosRow this[int index] {
                get {
                    return ((RolEgresosRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event RolEgresosRowChangeEventHandler RolEgresosRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event RolEgresosRowChangeEventHandler RolEgresosRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event RolEgresosRowChangeEventHandler RolEgresosRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event RolEgresosRowChangeEventHandler RolEgresosRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddRolEgresosRow(RolEgresosRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosRow AddRolEgresosRow(
                        string ID, 
                        string CEDULA, 
                        string EMPLEADO, 
                        string DEPARTAMENTO, 
                        string DIAS_LABORADOS, 
                        string TOTAL_INGRESOS_IESS, 
                        string TOTAL_INGRESOS_NO_IESS, 
                        string TOTAL_INGRESOS, 
                        string APORTE_IESS_EMPLEADO, 
                        string APORTE_IESS_CONYUGE_EMPLEADO, 
                        string ANTICIPO_SUELDO, 
                        string ANTICIPO_ALIMENTACION, 
                        string DESCUENTO_DE_HABERES, 
                        string DESCUENTO_CELULAR, 
                        string VACACIONES_PAGADAS, 
                        string PRESTAMO_HIPOTECARIO, 
                        string PRESTAMO_QUIROGRAFARIO, 
                        string PRESTAMO_INTERNO, 
                        string RETENCION_JUDICIAL, 
                        string OTROS_EGRESOS, 
                        string NETO_A_RECIBIR, 
                        string IMPUESTO_A_LA_RENTA, 
                        string TOTAL_EGRESOS) {
                RolEgresosRow rowRolEgresosRow = ((RolEgresosRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ID,
                        CEDULA,
                        EMPLEADO,
                        DEPARTAMENTO,
                        DIAS_LABORADOS,
                        TOTAL_INGRESOS_IESS,
                        TOTAL_INGRESOS_NO_IESS,
                        TOTAL_INGRESOS,
                        APORTE_IESS_EMPLEADO,
                        APORTE_IESS_CONYUGE_EMPLEADO,
                        ANTICIPO_SUELDO,
                        ANTICIPO_ALIMENTACION,
                        DESCUENTO_DE_HABERES,
                        DESCUENTO_CELULAR,
                        VACACIONES_PAGADAS,
                        PRESTAMO_HIPOTECARIO,
                        PRESTAMO_QUIROGRAFARIO,
                        PRESTAMO_INTERNO,
                        RETENCION_JUDICIAL,
                        OTROS_EGRESOS,
                        NETO_A_RECIBIR,
                        IMPUESTO_A_LA_RENTA,
                        TOTAL_EGRESOS};
                rowRolEgresosRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRolEgresosRow);
                return rowRolEgresosRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                RolEgresosDataTable cln = ((RolEgresosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RolEgresosDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnID = base.Columns["ID"];
                this.columnCEDULA = base.Columns["CEDULA"];
                this.columnEMPLEADO = base.Columns["EMPLEADO"];
                this.columnDEPARTAMENTO = base.Columns["DEPARTAMENTO"];
                this.columnDIAS_LABORADOS = base.Columns["DIAS LABORADOS"];
                this.columnTOTAL_INGRESOS_IESS = base.Columns["TOTAL INGRESOS IESS"];
                this.columnTOTAL_INGRESOS_NO_IESS = base.Columns["TOTAL INGRESOS NO IESS"];
                this.columnTOTAL_INGRESOS = base.Columns["TOTAL INGRESOS"];
                this.columnAPORTE_IESS_EMPLEADO = base.Columns["APORTE IESS EMPLEADO"];
                this.columnAPORTE_IESS_CONYUGE_EMPLEADO = base.Columns["APORTE IESS CONYUGE EMPLEADO"];
                this.columnANTICIPO_SUELDO = base.Columns["ANTICIPO SUELDO"];
                this.columnANTICIPO_ALIMENTACION = base.Columns["ANTICIPO ALIMENTACION"];
                this.columnDESCUENTO_DE_HABERES = base.Columns["DESCUENTO DE HABERES"];
                this.columnDESCUENTO_CELULAR = base.Columns["DESCUENTO CELULAR"];
                this.columnVACACIONES_PAGADAS = base.Columns["VACACIONES PAGADAS"];
                this.columnPRESTAMO_HIPOTECARIO = base.Columns["PRESTAMO HIPOTECARIO"];
                this.columnPRESTAMO_QUIROGRAFARIO = base.Columns["PRESTAMO QUIROGRAFARIO"];
                this.columnPRESTAMO_INTERNO = base.Columns["PRESTAMO INTERNO"];
                this.columnRETENCION_JUDICIAL = base.Columns["RETENCION JUDICIAL"];
                this.columnOTROS_EGRESOS = base.Columns["OTROS EGRESOS"];
                this.columnNETO_A_RECIBIR = base.Columns["NETO A RECIBIR"];
                this.columnIMPUESTO_A_LA_RENTA = base.Columns["IMPUESTO A LA RENTA"];
                this.columnTOTAL_EGRESOS = base.Columns["TOTAL EGRESOS"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnID = new global::System.Data.DataColumn("ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnID);
                this.columnCEDULA = new global::System.Data.DataColumn("CEDULA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCEDULA);
                this.columnEMPLEADO = new global::System.Data.DataColumn("EMPLEADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMPLEADO);
                this.columnDEPARTAMENTO = new global::System.Data.DataColumn("DEPARTAMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDEPARTAMENTO);
                this.columnDIAS_LABORADOS = new global::System.Data.DataColumn("DIAS LABORADOS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIAS_LABORADOS);
                this.columnTOTAL_INGRESOS_IESS = new global::System.Data.DataColumn("TOTAL INGRESOS IESS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_INGRESOS_IESS);
                this.columnTOTAL_INGRESOS_NO_IESS = new global::System.Data.DataColumn("TOTAL INGRESOS NO IESS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_INGRESOS_NO_IESS);
                this.columnTOTAL_INGRESOS = new global::System.Data.DataColumn("TOTAL INGRESOS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_INGRESOS);
                this.columnAPORTE_IESS_EMPLEADO = new global::System.Data.DataColumn("APORTE IESS EMPLEADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAPORTE_IESS_EMPLEADO);
                this.columnAPORTE_IESS_CONYUGE_EMPLEADO = new global::System.Data.DataColumn("APORTE IESS CONYUGE EMPLEADO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAPORTE_IESS_CONYUGE_EMPLEADO);
                this.columnANTICIPO_SUELDO = new global::System.Data.DataColumn("ANTICIPO SUELDO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnANTICIPO_SUELDO);
                this.columnANTICIPO_ALIMENTACION = new global::System.Data.DataColumn("ANTICIPO ALIMENTACION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnANTICIPO_ALIMENTACION);
                this.columnDESCUENTO_DE_HABERES = new global::System.Data.DataColumn("DESCUENTO DE HABERES", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESCUENTO_DE_HABERES);
                this.columnDESCUENTO_CELULAR = new global::System.Data.DataColumn("DESCUENTO CELULAR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESCUENTO_CELULAR);
                this.columnVACACIONES_PAGADAS = new global::System.Data.DataColumn("VACACIONES PAGADAS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVACACIONES_PAGADAS);
                this.columnPRESTAMO_HIPOTECARIO = new global::System.Data.DataColumn("PRESTAMO HIPOTECARIO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRESTAMO_HIPOTECARIO);
                this.columnPRESTAMO_QUIROGRAFARIO = new global::System.Data.DataColumn("PRESTAMO QUIROGRAFARIO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRESTAMO_QUIROGRAFARIO);
                this.columnPRESTAMO_INTERNO = new global::System.Data.DataColumn("PRESTAMO INTERNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRESTAMO_INTERNO);
                this.columnRETENCION_JUDICIAL = new global::System.Data.DataColumn("RETENCION JUDICIAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETENCION_JUDICIAL);
                this.columnOTROS_EGRESOS = new global::System.Data.DataColumn("OTROS EGRESOS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOTROS_EGRESOS);
                this.columnNETO_A_RECIBIR = new global::System.Data.DataColumn("NETO A RECIBIR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNETO_A_RECIBIR);
                this.columnIMPUESTO_A_LA_RENTA = new global::System.Data.DataColumn("IMPUESTO A LA RENTA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIMPUESTO_A_LA_RENTA);
                this.columnTOTAL_EGRESOS = new global::System.Data.DataColumn("TOTAL EGRESOS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL_EGRESOS);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosRow NewRolEgresosRow() {
                return ((RolEgresosRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RolEgresosRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(RolEgresosRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RolEgresosRowChanged != null)) {
                    this.RolEgresosRowChanged(this, new RolEgresosRowChangeEvent(((RolEgresosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RolEgresosRowChanging != null)) {
                    this.RolEgresosRowChanging(this, new RolEgresosRowChangeEvent(((RolEgresosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RolEgresosRowDeleted != null)) {
                    this.RolEgresosRowDeleted(this, new RolEgresosRowChangeEvent(((RolEgresosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RolEgresosRowDeleting != null)) {
                    this.RolEgresosRowDeleting(this, new RolEgresosRowChangeEvent(((RolEgresosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveRolEgresosRow(RolEgresosRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRolIngresos ds = new dsRolIngresos();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RolEgresosDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class RolEgresosRow : global::System.Data.DataRow {
            
            private RolEgresosDataTable tableRolEgresos;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal RolEgresosRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRolEgresos = ((RolEgresosDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ID {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ID\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CEDULA {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.CEDULAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CEDULA\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.CEDULAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string EMPLEADO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'EMPLEADO\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DEPARTAMENTO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.DEPARTAMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DEPARTAMENTO\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.DEPARTAMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DIAS_LABORADOS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.DIAS_LABORADOSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DIAS LABORADOS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.DIAS_LABORADOSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TOTAL_INGRESOS_IESS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.TOTAL_INGRESOS_IESSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL INGRESOS IESS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.TOTAL_INGRESOS_IESSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TOTAL_INGRESOS_NO_IESS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.TOTAL_INGRESOS_NO_IESSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL INGRESOS NO IESS\' de la tabla \'RolEgresos\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.TOTAL_INGRESOS_NO_IESSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TOTAL_INGRESOS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.TOTAL_INGRESOSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL INGRESOS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.TOTAL_INGRESOSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string APORTE_IESS_EMPLEADO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.APORTE_IESS_EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'APORTE IESS EMPLEADO\' de la tabla \'RolEgresos\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.APORTE_IESS_EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string APORTE_IESS_CONYUGE_EMPLEADO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.APORTE_IESS_CONYUGE_EMPLEADOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'APORTE IESS CONYUGE EMPLEADO\' de la tabla \'RolEgresos\' es" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.APORTE_IESS_CONYUGE_EMPLEADOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ANTICIPO_SUELDO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.ANTICIPO_SUELDOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ANTICIPO SUELDO\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.ANTICIPO_SUELDOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ANTICIPO_ALIMENTACION {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.ANTICIPO_ALIMENTACIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ANTICIPO ALIMENTACION\' de la tabla \'RolEgresos\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.ANTICIPO_ALIMENTACIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DESCUENTO_DE_HABERES {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.DESCUENTO_DE_HABERESColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DESCUENTO DE HABERES\' de la tabla \'RolEgresos\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.DESCUENTO_DE_HABERESColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DESCUENTO_CELULAR {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.DESCUENTO_CELULARColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'DESCUENTO CELULAR\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.DESCUENTO_CELULARColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string VACACIONES_PAGADAS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.VACACIONES_PAGADASColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'VACACIONES PAGADAS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.VACACIONES_PAGADASColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PRESTAMO_HIPOTECARIO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.PRESTAMO_HIPOTECARIOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PRESTAMO HIPOTECARIO\' de la tabla \'RolEgresos\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.PRESTAMO_HIPOTECARIOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PRESTAMO_QUIROGRAFARIO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.PRESTAMO_QUIROGRAFARIOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PRESTAMO QUIROGRAFARIO\' de la tabla \'RolEgresos\' es DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.PRESTAMO_QUIROGRAFARIOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PRESTAMO_INTERNO {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.PRESTAMO_INTERNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PRESTAMO INTERNO\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.PRESTAMO_INTERNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string RETENCION_JUDICIAL {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.RETENCION_JUDICIALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'RETENCION JUDICIAL\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.RETENCION_JUDICIALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string OTROS_EGRESOS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.OTROS_EGRESOSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'OTROS EGRESOS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.OTROS_EGRESOSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string NETO_A_RECIBIR {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.NETO_A_RECIBIRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'NETO A RECIBIR\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.NETO_A_RECIBIRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string IMPUESTO_A_LA_RENTA {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.IMPUESTO_A_LA_RENTAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'IMPUESTO A LA RENTA\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.IMPUESTO_A_LA_RENTAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TOTAL_EGRESOS {
                get {
                    try {
                        return ((string)(this[this.tableRolEgresos.TOTAL_EGRESOSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TOTAL EGRESOS\' de la tabla \'RolEgresos\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableRolEgresos.TOTAL_EGRESOSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsIDNull() {
                return this.IsNull(this.tableRolEgresos.IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetIDNull() {
                this[this.tableRolEgresos.IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCEDULANull() {
                return this.IsNull(this.tableRolEgresos.CEDULAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCEDULANull() {
                this[this.tableRolEgresos.CEDULAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsEMPLEADONull() {
                return this.IsNull(this.tableRolEgresos.EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetEMPLEADONull() {
                this[this.tableRolEgresos.EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDEPARTAMENTONull() {
                return this.IsNull(this.tableRolEgresos.DEPARTAMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDEPARTAMENTONull() {
                this[this.tableRolEgresos.DEPARTAMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDIAS_LABORADOSNull() {
                return this.IsNull(this.tableRolEgresos.DIAS_LABORADOSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDIAS_LABORADOSNull() {
                this[this.tableRolEgresos.DIAS_LABORADOSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTOTAL_INGRESOS_IESSNull() {
                return this.IsNull(this.tableRolEgresos.TOTAL_INGRESOS_IESSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTOTAL_INGRESOS_IESSNull() {
                this[this.tableRolEgresos.TOTAL_INGRESOS_IESSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTOTAL_INGRESOS_NO_IESSNull() {
                return this.IsNull(this.tableRolEgresos.TOTAL_INGRESOS_NO_IESSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTOTAL_INGRESOS_NO_IESSNull() {
                this[this.tableRolEgresos.TOTAL_INGRESOS_NO_IESSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTOTAL_INGRESOSNull() {
                return this.IsNull(this.tableRolEgresos.TOTAL_INGRESOSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTOTAL_INGRESOSNull() {
                this[this.tableRolEgresos.TOTAL_INGRESOSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsAPORTE_IESS_EMPLEADONull() {
                return this.IsNull(this.tableRolEgresos.APORTE_IESS_EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetAPORTE_IESS_EMPLEADONull() {
                this[this.tableRolEgresos.APORTE_IESS_EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsAPORTE_IESS_CONYUGE_EMPLEADONull() {
                return this.IsNull(this.tableRolEgresos.APORTE_IESS_CONYUGE_EMPLEADOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetAPORTE_IESS_CONYUGE_EMPLEADONull() {
                this[this.tableRolEgresos.APORTE_IESS_CONYUGE_EMPLEADOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsANTICIPO_SUELDONull() {
                return this.IsNull(this.tableRolEgresos.ANTICIPO_SUELDOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetANTICIPO_SUELDONull() {
                this[this.tableRolEgresos.ANTICIPO_SUELDOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsANTICIPO_ALIMENTACIONNull() {
                return this.IsNull(this.tableRolEgresos.ANTICIPO_ALIMENTACIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetANTICIPO_ALIMENTACIONNull() {
                this[this.tableRolEgresos.ANTICIPO_ALIMENTACIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDESCUENTO_DE_HABERESNull() {
                return this.IsNull(this.tableRolEgresos.DESCUENTO_DE_HABERESColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDESCUENTO_DE_HABERESNull() {
                this[this.tableRolEgresos.DESCUENTO_DE_HABERESColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDESCUENTO_CELULARNull() {
                return this.IsNull(this.tableRolEgresos.DESCUENTO_CELULARColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDESCUENTO_CELULARNull() {
                this[this.tableRolEgresos.DESCUENTO_CELULARColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsVACACIONES_PAGADASNull() {
                return this.IsNull(this.tableRolEgresos.VACACIONES_PAGADASColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetVACACIONES_PAGADASNull() {
                this[this.tableRolEgresos.VACACIONES_PAGADASColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPRESTAMO_HIPOTECARIONull() {
                return this.IsNull(this.tableRolEgresos.PRESTAMO_HIPOTECARIOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPRESTAMO_HIPOTECARIONull() {
                this[this.tableRolEgresos.PRESTAMO_HIPOTECARIOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPRESTAMO_QUIROGRAFARIONull() {
                return this.IsNull(this.tableRolEgresos.PRESTAMO_QUIROGRAFARIOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPRESTAMO_QUIROGRAFARIONull() {
                this[this.tableRolEgresos.PRESTAMO_QUIROGRAFARIOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPRESTAMO_INTERNONull() {
                return this.IsNull(this.tableRolEgresos.PRESTAMO_INTERNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPRESTAMO_INTERNONull() {
                this[this.tableRolEgresos.PRESTAMO_INTERNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsRETENCION_JUDICIALNull() {
                return this.IsNull(this.tableRolEgresos.RETENCION_JUDICIALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetRETENCION_JUDICIALNull() {
                this[this.tableRolEgresos.RETENCION_JUDICIALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsOTROS_EGRESOSNull() {
                return this.IsNull(this.tableRolEgresos.OTROS_EGRESOSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetOTROS_EGRESOSNull() {
                this[this.tableRolEgresos.OTROS_EGRESOSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsNETO_A_RECIBIRNull() {
                return this.IsNull(this.tableRolEgresos.NETO_A_RECIBIRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetNETO_A_RECIBIRNull() {
                this[this.tableRolEgresos.NETO_A_RECIBIRColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsIMPUESTO_A_LA_RENTANull() {
                return this.IsNull(this.tableRolEgresos.IMPUESTO_A_LA_RENTAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetIMPUESTO_A_LA_RENTANull() {
                this[this.tableRolEgresos.IMPUESTO_A_LA_RENTAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTOTAL_EGRESOSNull() {
                return this.IsNull(this.tableRolEgresos.TOTAL_EGRESOSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTOTAL_EGRESOSNull() {
                this[this.tableRolEgresos.TOTAL_EGRESOSColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class RolEgresosRowChangeEvent : global::System.EventArgs {
            
            private RolEgresosRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosRowChangeEvent(RolEgresosRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public RolEgresosRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591