//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFIPITEMACTIVOFIJO
    {
        public int IdItemActivoFijo { get; set; }
        public string CodigoEstado { get; set; }
        public string Descripcion { get; set; }
        public string CodigoTipoActivoFijo { get; set; }
        public string CodigoSucursal { get; set; }
        public string CodigoCentroCosto { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public System.DateTime FechaActivacion { get; set; }
        public decimal CostoCompra { get; set; }
        public decimal ValorResidual { get; set; }
        public decimal ValorDepreciable { get; set; }
        public decimal DepreciacionAcumulada { get; set; }
        public decimal CostoActual { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<bool> Depreciado { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string ProductId { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string Persona { get; set; }
        public string CodigoAgrupacion { get; set; }
        public string Agrupacion { get; set; }
        public string NumFactura { get; set; }
        public string CodigoEstadoActivoFijo { get; set; }
        public string NombreOriginal { get; set; }
        public string ArchivoAdjunto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Proveedor { get; set; }
    }
}
