//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFITMOVIMIENTOACTIVOFIJO
    {
        public int IdMovimientoActivoFijo { get; set; }
        public string CodigoEstado { get; set; }
        public string CodigoTipoMovimiento { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public int IdItemActivoFijo { get; set; }
        public decimal CostoCompra { get; set; }
        public decimal ValorResidual { get; set; }
        public decimal ValorDepreciable { get; set; }
        public decimal DepreciacionAcumulada { get; set; }
        public decimal CostoActual { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> ValorVenta { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string CodigoEstadoActivoFijoAnt { get; set; }
        public string ActivoFijo { get; set; }
    }
}
