//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBTCOMISIONESDETALLE
    {
        public int IdComisionesDetalle { get; set; }
        public string CodigoEstado { get; set; }
        public int IdComisiones { get; set; }
        public int CodVendedor { get; set; }
        public string NomVendedor { get; set; }
        public string CodCliente { get; set; }
        public string GrupoCliente { get; set; }
        public string NumFactura { get; set; }
        public string Titular { get; set; }
        public string CodicionPago { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVecimineto { get; set; }
        public System.DateTime FechaContabilizacion { get; set; }
        public System.DateTime FechaEfectiva { get; set; }
        public int NumDocPago { get; set; }
        public string Recaudador { get; set; }
        public string TipoDoc { get; set; }
        public string NoCheque { get; set; }
        public string CodBanco { get; set; }
        public string NomBanco { get; set; }
        public decimal ValorTotal { get; set; }
        public decimal ValorCuenta { get; set; }
        public decimal Valor { get; set; }
        public string NomEmpresa { get; set; }
        public string CodeZona { get; set; }
        public string NameZona { get; set; }
        public string CodeZonaMod { get; set; }
        public string NameZonaMod { get; set; }
        public int DiasPago { get; set; }
        public Nullable<int> DiasPagoMod { get; set; }
        public bool Considerado { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string Ingreso { get; set; }
        public Nullable<decimal> PorcentajeRTC { get; set; }
        public Nullable<decimal> PorcentajeJBO { get; set; }
        public Nullable<decimal> PorcentajeABO { get; set; }
        public Nullable<decimal> PorcentajePTC { get; set; }
        public Nullable<decimal> PorcentajeFMA { get; set; }
        public Nullable<decimal> ComisionRTC { get; set; }
        public Nullable<decimal> ComisionJBO { get; set; }
        public Nullable<decimal> ComisionABO { get; set; }
        public Nullable<decimal> ComisionPTC { get; set; }
        public Nullable<decimal> ComisionFMA { get; set; }
        public Nullable<bool> ConsideradoCobranza { get; set; }
        public Nullable<int> DiasDocumento { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdReferencialExcepcion { get; set; }
        public Nullable<int> DiasDocumentoAdd { get; set; }
    
        public virtual COBTCOMISIONES COBTCOMISIONES { get; set; }
    }
}
