//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBTSEGUIMIENTOCOMPROMISO
    {
        public int IdSeguimientoCompromiso { get; set; }
        public string CodigoEstado { get; set; }
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string CodCliente { get; set; }
        public string Cliente { get; set; }
        public string CodZona { get; set; }
        public string Zona { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public int NumCompromiso { get; set; }
        public decimal ValorPedido { get; set; }
        public string Factura { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaCompromiso { get; set; }
        public int DiasMora { get; set; }
        public string Compromiso { get; set; }
        public string CompromisoCumplido { get; set; }
        public string Observaciones { get; set; }
        public string CodigoMotivo { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
    }
}
