//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMTCOTIZACIONPROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMTCOTIZACIONPROVEEDOR()
        {
            this.COMTCOTIZACIONPROVEEDORADJUNTO = new HashSet<COMTCOTIZACIONPROVEEDORADJUNTO>();
            this.COMTCOTIZACIONPROVEEDORDETALLE = new HashSet<COMTCOTIZACIONPROVEEDORDETALLE>();
        }
    
        public int IdCotizacionProveedor { get; set; }
        public string CodigoEstado { get; set; }
        public int IdCotizacion { get; set; }
        public string IdentificacionProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string CodigoUsuarioAprobacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<decimal> TotalProveedor { get; set; }
        public System.DateTime FechaCotizacion { get; set; }
        public int DiasEntrega { get; set; }
        public string FormaPago { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> ValorIva { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> RequiereAnticipo { get; set; }
        public Nullable<decimal> ValorAnticipo { get; set; }
        public Nullable<int> DiasPago { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual COMTCOTIZACION COMTCOTIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMTCOTIZACIONPROVEEDORADJUNTO> COMTCOTIZACIONPROVEEDORADJUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMTCOTIZACIONPROVEEDORDETALLE> COMTCOTIZACIONPROVEEDORDETALLE { get; set; }
    }
}
