//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMTORDENCOMPRAPROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMTORDENCOMPRAPROVEEDOR()
        {
            this.COMTORDENCOMPRAPROVEEDORITEM = new HashSet<COMTORDENCOMPRAPROVEEDORITEM>();
        }
    
        public int IdOrdenCompraProveedor { get; set; }
        public int IdOrdenCompra { get; set; }
        public string IdentificacionProveedor { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string CodigoEstado { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<decimal> TotalProveedor { get; set; }
        public Nullable<decimal> ValorIva { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<bool> RequiereAnticipo { get; set; }
        public Nullable<decimal> ValorAnticipo { get; set; }
        public string FormaPago { get; set; }
        public Nullable<System.DateTime> FechaEntregaEstimada { get; set; }
        public string Observacion { get; set; }
        public string Correo { get; set; }
        public Nullable<bool> CorreoEnviado { get; set; }
        public Nullable<bool> AnticipoIngresado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual COMTORDENCOMPRA COMTORDENCOMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMTORDENCOMPRAPROVEEDORITEM> COMTORDENCOMPRAPROVEEDORITEM { get; set; }
    }
}
