//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRETPROCESOCREDITOCEDULA
    {
        public int IdProcesoCredito { get; set; }
        public string IdentificacionRepLegal { get; set; }
        public Nullable<System.DateTime> FechaCaducidadCedulaRepLegal { get; set; }
        public string NombreRepLegal { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string CodigoEstadoCivil { get; set; }
        public string IdentificacionConyuge { get; set; }
        public string NombreConyuge { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ComentarioRevisionCedula { get; set; }
    
        public virtual CRETPROCESOCREDITO CRETPROCESOCREDITO { get; set; }
    }
}
