//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRETPLANTILLASEGURO
    {
        public int IdPlantillaSeguro { get; set; }
        public string CodigoEstado { get; set; }
        public string Pais { get; set; }
        public string Ruc { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string PersonaContacto { get; set; }
        public string CorreoElectronico { get; set; }
        public decimal CupoSolicitado { get; set; }
        public decimal ProyeccionVentasAnuales { get; set; }
        public int PlazoCreditoSolicitado { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<int> IdProcesoCredito { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<decimal> CreditoAprobado { get; set; }
        public Nullable<int> PlazoAprobado { get; set; }
        public string Estado { get; set; }
        public string ObservacionesSeguro { get; set; }
        public string Comentarios { get; set; }
        public string FechaRevision { get; set; }
        public string NombreOriginal { get; set; }
        public string ArchivoAdjunto { get; set; }
    }
}
