//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRETPROCESOCREDITORUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRETPROCESOCREDITORUC()
        {
            this.CRETPROCESOCREDITORUCDIRECCION = new HashSet<CRETPROCESOCREDITORUCDIRECCION>();
        }
    
        public int IdProcesoCredito { get; set; }
        public string Identificacion { get; set; }
        public string NombreComercial { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string EstadoRuc { get; set; }
        public string ObligadoLlevarCantidadRuc { get; set; }
        public Nullable<System.DateTime> FechaInicioActividadRuc { get; set; }
        public Nullable<System.DateTime> FechaReinicioActividadRuc { get; set; }
        public Nullable<System.DateTime> FechaUltActualizacionRuc { get; set; }
        public string CodigoTipoNegocio { get; set; }
        public string ActividadesSecundarias { get; set; }
        public string OtrasActividades { get; set; }
        public string Comentarios { get; set; }
    
        public virtual CRETPROCESOCREDITO CRETPROCESOCREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETPROCESOCREDITORUCDIRECCION> CRETPROCESOCREDITORUCDIRECCION { get; set; }
    }
}
