//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRETINFORMERTC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRETINFORMERTC()
        {
            this.CRETINFORMERTCCLIENTES = new HashSet<CRETINFORMERTCCLIENTES>();
            this.CRETINFORMERTCCROQUIS = new HashSet<CRETINFORMERTCCROQUIS>();
            this.CRETINFORMERTCCULTIVOS = new HashSet<CRETINFORMERTCCULTIVOS>();
            this.CRETINFORMERTCDOCUMENTOSPENDIENTES = new HashSet<CRETINFORMERTCDOCUMENTOSPENDIENTES>();
            this.CRETINFORMERTCPROVEEDOR = new HashSet<CRETINFORMERTCPROVEEDOR>();
            this.CRETINFORMERTCPRODUCTOS = new HashSet<CRETINFORMERTCPRODUCTOS>();
        }
    
        public int IdInformeRTC { get; set; }
        public string CodigoEstado { get; set; }
        public string CodigoTipoProceso { get; set; }
        public string TipoProceso { get; set; }
        public string CodigoActividadCliente { get; set; }
        public string ActividadCliente { get; set; }
        public int IdRTC { get; set; }
        public string RTC { get; set; }
        public string Zona { get; set; }
        public string CodigoCliente { get; set; }
        public string Cliente { get; set; }
        public string RepresentanteLegal { get; set; }
        public string CodigoTipoPersona { get; set; }
        public string CodigoSector { get; set; }
        public System.DateTime FechaInforme { get; set; }
        public string Ciudad { get; set; }
        public int TiempoEnZonaActividad { get; set; }
        public string ZonasCubrenVentas { get; set; }
        public string TipoCultivo { get; set; }
        public decimal CantidadHectareasCubreVentas { get; set; }
        public string CultivosSiembra { get; set; }
        public decimal CantidadHectareasSembradasCultivo { get; set; }
        public decimal CostoHectarea { get; set; }
        public decimal PotencialVenta { get; set; }
        public decimal CantidadHectareasPropias { get; set; }
        public decimal CantidadHectareasAlquiladas { get; set; }
        public string TieneCodigoSap { get; set; }
        public string GrupoSap { get; set; }
        public decimal TotalHectareas { get; set; }
        public string TieneOtrasActividadesComerciales { get; set; }
        public decimal MontoAnualesVenta { get; set; }
        public string TieneCuencaCorriente { get; set; }
        public string CodigoBanco { get; set; }
        public string Banco { get; set; }
        public string DetalleFormaPago { get; set; }
        public string TrabajadoAntesCliente { get; set; }
        public string Donde { get; set; }
        public int TiempoConocerlo { get; set; }
        public string ComportamientoPago { get; set; }
        public string TieneHistorialAfecor { get; set; }
        public decimal CupoSolicitado { get; set; }
        public decimal VentaEstimadaAnual { get; set; }
        public int PlazoSolicitado { get; set; }
        public decimal Mes1 { get; set; }
        public decimal Mes2 { get; set; }
        public decimal Mes3 { get; set; }
        public decimal Mes4 { get; set; }
        public decimal Mes5 { get; set; }
        public decimal Mes6 { get; set; }
        public decimal Mes7 { get; set; }
        public decimal Mes8 { get; set; }
        public decimal Mes9 { get; set; }
        public decimal Mes10 { get; set; }
        public decimal Mes11 { get; set; }
        public decimal Mes12 { get; set; }
        public decimal VentasSri { get; set; }
        public decimal ComprasSri { get; set; }
        public decimal FacturacionAfecor { get; set; }
        public decimal PorcAfecorSobreCompras { get; set; }
        public decimal PorcAfecorSobreComprasProyectadas { get; set; }
        public decimal MontoCrecimientoAfecor { get; set; }
        public decimal PorcCrecimientoAfecor { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<int> IdReferenciaForm { get; set; }
        public Nullable<bool> Completado { get; set; }
        public Nullable<int> IdProcesoCredito { get; set; }
        public string Argumentos { get; set; }
        public string Direccion1Almacen { get; set; }
        public string Direccion1Titular { get; set; }
        public string Direccion2Almacen { get; set; }
        public string Direccion2Titular { get; set; }
        public Nullable<int> TiempoConocerloMes { get; set; }
        public Nullable<int> TiempoEnZonaActividadMes { get; set; }
        public Nullable<decimal> MontoHistorialCompras { get; set; }
        public Nullable<System.DateTime> FechaUltimaSolicitud { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCCLIENTES> CRETINFORMERTCCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCCROQUIS> CRETINFORMERTCCROQUIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCCULTIVOS> CRETINFORMERTCCULTIVOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCDOCUMENTOSPENDIENTES> CRETINFORMERTCDOCUMENTOSPENDIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCPROVEEDOR> CRETINFORMERTCPROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRETINFORMERTCPRODUCTOS> CRETINFORMERTCPRODUCTOS { get; set; }
    }
}
