//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENLPERSONA
    {
        public int Id { get; set; }
        public int IdPersona { get; set; }
        public string CodigoEstado { get; set; }
        public string CodigoTipoPersona { get; set; }
        public string CodigoTipoIdentificacion { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string NombreCompleto { get; set; }
        public string Correo { get; set; }
        public string CodigoEstadoCivil { get; set; }
        public string CodigoGenero { get; set; }
        public string LugarNacimiento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string RutaImagen { get; set; }
        public string CodigoNivelEducacion { get; set; }
        public string NumeroRegistroProfesional { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Estatura { get; set; }
        public string CodigoColorPiel { get; set; }
        public string CodigoColorOjos { get; set; }
        public string CodigoTipoSangre { get; set; }
        public string CodigoTipoLicencia { get; set; }
        public Nullable<System.DateTime> FechaExpiracionLicencia { get; set; }
        public string NumeroLicencia { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string CodigoRegion { get; set; }
        public Nullable<bool> DescuentaIR { get; set; }
        public string CodigoTipoDiscapacidad { get; set; }
        public Nullable<decimal> PorcentajeDiscapacidad { get; set; }
        public System.DateTime FechaTrigger { get; set; }
    }
}
