//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENMPERSONAFICHAMEDICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GENMPERSONAFICHAMEDICA()
        {
            this.GENMPERSONAFICHAMEDICAADJUNTO = new HashSet<GENMPERSONAFICHAMEDICAADJUNTO>();
        }
    
        public int IdPersonaFichaMedica { get; set; }
        public string CodigoEstado { get; set; }
        public int IdPersona { get; set; }
        public string CodigoTipo { get; set; }
        public decimal Peso { get; set; }
        public string CodigoTipoSangre { get; set; }
        public decimal Estatura { get; set; }
        public decimal IMC { get; set; }
        public decimal ParametroAbdominal { get; set; }
        public string PresionArterial { get; set; }
        public decimal FrecuenciaCardiaca { get; set; }
        public decimal Temperatura { get; set; }
        public decimal Saturacion { get; set; }
        public bool AtencionPrioritaria { get; set; }
        public string EnfermedadesPreexistentes { get; set; }
        public string AntecedentesFamiliares { get; set; }
        public string Piel { get; set; }
        public string Ojos { get; set; }
        public System.DateTime Periodo { get; set; }
        public string Observaciones { get; set; }
        public string Diagnostico { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string Alergias { get; set; }
        public string MedicacionContinua { get; set; }
        public string AntecedentesQuirurgicos { get; set; }
        public string CodigoEstadoIMC { get; set; }
        public string CIE10 { get; set; }
    
        public virtual GENMPERSONA GENMPERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENMPERSONAFICHAMEDICAADJUNTO> GENMPERSONAFICHAMEDICAADJUNTO { get; set; }
    }
}
