//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class REHMTIPOCONTRATO
    {
        public string CodigoTipoContrato { get; set; }
        public string CodigoEstado { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<bool> AsumeIessEmpresa { get; set; }
        public Nullable<bool> PagoVacacionesMensual { get; set; }
        public Nullable<bool> PagoUtilidades { get; set; }
        public Nullable<decimal> PorcAportePersonal { get; set; }
        public Nullable<decimal> PorcAportePatronal { get; set; }
        public Nullable<decimal> PorcAporteSecap { get; set; }
        public Nullable<bool> ProvisionVac { get; set; }
        public Nullable<bool> ProvisionD3 { get; set; }
        public Nullable<bool> ProvisionD4 { get; set; }
    }
}
