//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class REHPRUBRO
    {
        public string CodigoRubro { get; set; }
        public string CodigoEstado { get; set; }
        public string Descripcion { get; set; }
        public string CodigoTipoRubro { get; set; }
        public Nullable<bool> Iess { get; set; }
        public string CodigoRubroContraPartida { get; set; }
        public string CodigoCategoriaRubro { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<bool> NovedadEditable { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> EsEntero { get; set; }
        public string Formula { get; set; }
        public Nullable<bool> ImpuestoRenta { get; set; }
        public string CodigoTipoContabilizacion { get; set; }
        public string CodigoTipoMovimiento { get; set; }
    }
}
