//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class REHTNOMINACONSOLIDADO
    {
        public int IdNominaConsolidado { get; set; }
        public string CodigoEstado { get; set; }
        public int Anio { get; set; }
        public string Mes { get; set; }
        public string CodigoTipoRol { get; set; }
        public int IdPersona { get; set; }
        public decimal ValorBaseAjuste { get; set; }
        public decimal ValorBaseProvision { get; set; }
        public decimal ValorAjuste { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
    }
}
