//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class REHVTPERSONACONTRATO
    {
        public int IdPersona { get; set; }
        public int IdEmpleadoContrato { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string NombreCompleto { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Region { get; set; }
        public string EstadoCivil { get; set; }
        public string RutaImagen { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreoLaboral { get; set; }
        public string TipoEmpleado { get; set; }
        public string Sucursal { get; set; }
        public string CentroCosto { get; set; }
        public string Departamento { get; set; }
        public string CargoLaboral { get; set; }
        public System.DateTime FechaInicioContrato { get; set; }
        public decimal Sueldo { get; set; }
        public string Banco { get; set; }
        public string FormaPago { get; set; }
        public string NumeroCuenta { get; set; }
        public string TipoComision { get; set; }
        public Nullable<decimal> PorcentajeComision { get; set; }
        public Nullable<decimal> PorcentajeComisionAdicional { get; set; }
        public bool EsJubilado { get; set; }
        public bool AcumulaD13 { get; set; }
        public bool AcumulaD14 { get; set; }
        public Nullable<decimal> PorcentajeDiscapacidad { get; set; }
        public Nullable<System.DateTime> FechaIngresoMandatoOcho { get; set; }
        public string CodigoSectorial { get; set; }
        public string TipoContrato { get; set; }
        public string Extension { get; set; }
        public string CelularLaboral { get; set; }
        public string CodigoCargoLaboral { get; set; }
    }
}
