//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGMUSUARIO
    {
        public string CodigoUsuario { get; set; }
        public string CodigoEstado { get; set; }
        public string NombreCompleto { get; set; }
        public string Clave { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public Nullable<decimal> TamanoMB { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public string CodigoDepartamento { get; set; }
        public Nullable<bool> AprobacionFinalCotizacion { get; set; }
        public Nullable<System.TimeSpan> HoraInicioNotificacion { get; set; }
        public Nullable<System.TimeSpan> HoraFinNotificacion { get; set; }
        public Nullable<int> MinFrecuenciaNotificacion { get; set; }
        public string Correo { get; set; }
        public Nullable<decimal> MontoMaxCompra { get; set; }
        public Nullable<bool> EditaProveedorFormaPago { get; set; }
        public Nullable<int> CantidadMinCotizaciones { get; set; }
        public Nullable<bool> SuperUsuario { get; set; }
        public Nullable<bool> EditaTipoOrdenPago { get; set; }
        public Nullable<bool> VisualizaZonaOrdenPago { get; set; }
        public Nullable<bool> EnviarDesdeCorreoCorporativo { get; set; }
        public string ClaveDesdeCorreoCorporativo { get; set; }
        public string CorreoCorporativo { get; set; }
        public string CodigoUsuarioSap { get; set; }
        public Nullable<bool> ControlaDuplicidadGuias { get; set; }
        public Nullable<int> BodegaEPP { get; set; }
        public string TokenApi { get; set; }
    }
}
