//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHETCONTROLCALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHETCONTROLCALIDAD()
        {
            this.SHETCONTROLCALIDADDETALLE = new HashSet<SHETCONTROLCALIDADDETALLE>();
        }
    
        public int IdControlCalidad { get; set; }
        public string CodigoEstado { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Presentacion { get; set; }
        public string Empaque { get; set; }
        public string Lote { get; set; }
        public string TipoEnvasado { get; set; }
        public string Trazabilidad { get; set; }
        public System.DateTime FechaElaboracion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Produccion { get; set; }
        public string ObservacionesProduccion { get; set; }
        public int NumeroPersonalLinea { get; set; }
        public string UsoMascarilla { get; set; }
        public string UsoGuantes { get; set; }
        public string UsoGafas { get; set; }
        public string PisoLimpio { get; set; }
        public string MesaLimpia { get; set; }
        public string SoporteLimpio { get; set; }
        public string UsoLlenadora { get; set; }
        public string UsoSelladora { get; set; }
        public string UsoBalanza { get; set; }
        public string MaterialEmpaque { get; set; }
        public string UsoCaja { get; set; }
        public string UsoEtiqueta { get; set; }
        public string FechaCodEtiqueta { get; set; }
        public string LoteCodEtiqueta { get; set; }
        public string PvpCodEtiqueta { get; set; }
        public string RevisionDensidad { get; set; }
        public string RevisionVolumen { get; set; }
        public string RevisionColor { get; set; }
        public string ObservacionesPreparacionArea { get; set; }
        public string ControlMateriaPrima { get; set; }
        public Nullable<int> IdReferenciaForm { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string ResponsableLinea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHETCONTROLCALIDADDETALLE> SHETCONTROLCALIDADDETALLE { get; set; }
    }
}
