//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPNOMDETFIN
    {
        public int IdPersona { get; set; }
        public string TipoRubro { get; set; }
        public string CodigoRubro { get; set; }
        public string Rubro { get; set; }
        public string Descripcion { get; set; }
        public decimal Valor { get; set; }
        public int Dias { get; set; }
        public string CodigoTipoRol { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
    }
}
