//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTAPCAMPANAPUBLICITARIADESTINATARIO
    {
        public int IdCampanaPublicitariaDestinatario { get; set; }
        public string CodigoEstado { get; set; }
        public int IdCampanaPublicitaria { get; set; }
        public string EmailDestinatario { get; set; }
        public string EmailCC { get; set; }
        public bool Enviado { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual VTAPCAMPANAPUBLICITARIA VTAPCAMPANAPUBLICITARIA { get; set; }
    }
}
