//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTAPCAMPANAPUBLICITARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VTAPCAMPANAPUBLICITARIA()
        {
            this.VTAPCAMPANAPUBLICITARIAADJUNTO = new HashSet<VTAPCAMPANAPUBLICITARIAADJUNTO>();
            this.VTAPCAMPANAPUBLICITARIADESTINATARIO = new HashSet<VTAPCAMPANAPUBLICITARIADESTINATARIO>();
            this.VTAPCAMPANAPUBLICITARIACUERPO = new HashSet<VTAPCAMPANAPUBLICITARIACUERPO>();
        }
    
        public int IdCampanaPublicitaria { get; set; }
        public string CodigoEstado { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public string Asunto { get; set; }
        public string CuerpoDelEmail { get; set; }
        public string NombrePresentar { get; set; }
        public bool IsBodyHtml { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VTAPCAMPANAPUBLICITARIAADJUNTO> VTAPCAMPANAPUBLICITARIAADJUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VTAPCAMPANAPUBLICITARIADESTINATARIO> VTAPCAMPANAPUBLICITARIADESTINATARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VTAPCAMPANAPUBLICITARIACUERPO> VTAPCAMPANAPUBLICITARIACUERPO { get; set; }
    }
}
