//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTAPZONAGRUPODETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VTAPZONAGRUPODETALLE()
        {
            this.VTAPCARTERAZONASAPENVIOCORREO = new HashSet<VTAPCARTERAZONASAPENVIOCORREO>();
        }
    
        public int IdZonaGrupoDetalle { get; set; }
        public string CodigoEstado { get; set; }
        public int IdZonaGrupo { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
        public string CodAgrupacion { get; set; }
        public string Agrupacion { get; set; }
        public string CodResponsableCobranza { get; set; }
        public string ResponsableCobranza { get; set; }
        public Nullable<decimal> DiasProAcepIni { get; set; }
        public Nullable<decimal> DiasProAcepFin { get; set; }
        public Nullable<decimal> DiasProGestIni { get; set; }
        public Nullable<decimal> DiasProGestFin { get; set; }
        public Nullable<decimal> DiasProNoAcepIni { get; set; }
        public Nullable<decimal> DiasProNoAcepFin { get; set; }
        public Nullable<int> CodVendedor { get; set; }
        public string NomVendedor { get; set; }
        public Nullable<int> CodTitular { get; set; }
        public string Titular { get; set; }
        public Nullable<int> CodRecaudador { get; set; }
        public string Recaudador { get; set; }
    
        public virtual VTAPZONAGRUPO VTAPZONAGRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VTAPCARTERAZONASAPENVIOCORREO> VTAPCARTERAZONASAPENVIOCORREO { get; set; }
    }
}
