//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REH_Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTAPPRESUPUESTOREBATE
    {
        public int IdPresupuestoRebate { get; set; }
        public string CodigoEstado { get; set; }
        public int Periodo { get; set; }
        public int CodeVendedor { get; set; }
        public string NameVendedor { get; set; }
        public string CodeZona { get; set; }
        public string NameZona { get; set; }
        public string CodeCliente { get; set; }
        public string NameCliente { get; set; }
        public decimal Trimestre1 { get; set; }
        public decimal Trimestre2 { get; set; }
        public decimal Trimestre3 { get; set; }
        public decimal Trimestre4 { get; set; }
        public decimal Total { get; set; }
        public string Observacion { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string TerminalIngreso { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string TerminalModificacion { get; set; }
    }
}
